# Services for Bluestar Smart AC integration

bluestar_ac_force_sync:
  name: Force Sync Device
  description: Force sync a Bluestar Smart AC device to get the latest state
  fields:
    device_id:
      name: Device ID
      description: The device ID to force sync
      required: true
      selector:
        text:
