name: HACS Validation

on:
  push:
  pull_request:
  release:
    types: [published]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hacs/integration-action@main
        with:
          CATEGORY: integration
